version: '3.1'
services:
  app:
    container_name: nailcare
    image: springboot-postgresql
    build: ./
    ports:
      - "4000:4000"
    depends_on:
      - localhost
  localhost:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nailcare